"""Methodology view for precomputed simulation fan reports.

Reads ``reports/simulation_fan_*.csv`` artifacts generated by
``python -m src.models.simulation_fan``. This page visualizes those local
reports directly rather than calling FastAPI or regenerating simulations in
the dashboard.
"""

from __future__ import annotations

from pathlib import Path

import altair as alt
import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATHS = {
    "SARIMA (headline)": PROJECT_ROOT / "reports/simulation_fan_sarima.csv",
    "SARIMA (trimmed mean)": PROJECT_ROOT / "reports/simulation_fan_sarima_trimmed_mean.csv",
    "Elastic Net (headline)": PROJECT_ROOT / "reports/simulation_fan_elastic_net.csv",
    "Elastic Net (trimmed mean)": (
        PROJECT_ROOT / "reports/simulation_fan_elastic_net_trimmed_mean.csv"
    ),
    "Ensemble (headline)": PROJECT_ROOT / "reports/simulation_fan_ensemble.csv",
    "Ensemble (trimmed mean)": PROJECT_ROOT / "reports/simulation_fan_ensemble_trimmed_mean.csv",
    "SVAR (headline)": PROJECT_ROOT / "reports/simulation_fan_svar_headline.csv",
    "SVAR (trimmed mean)": PROJECT_ROOT / "reports/simulation_fan_svar_trimmed_mean.csv",
}

PALETTE = {
    "light": {"fan": "#eb6834", "median": "#a33d19", "muted": "#898781", "grid": "#e1e0d9"},
    "dark": {"fan": "#d95926", "median": "#ffb08f", "muted": "#898781", "grid": "#2c2c2a"},
}


@st.cache_data
def load_report(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)


def _current_theme() -> str:
    try:
        return st.context.theme.type or "light"
    except Exception:
        return "light"


def _display_path(path: Path) -> str:
    return path.relative_to(PROJECT_ROOT).as_posix()


def _fan_frame(report: pd.DataFrame) -> pd.DataFrame:
    frame = report.copy()
    frame["quarter_date"] = (
        pd.PeriodIndex(frame["target_quarter"], freq="Q").to_timestamp(how="end").normalize()
    )
    frame["horizon"] = pd.to_numeric(frame["horizon"], errors="coerce")
    return frame.sort_values("horizon")


def build_fan_chart(report: pd.DataFrame, theme_type: str) -> alt.LayerChart:
    colors = PALETTE[theme_type]
    outer_band = (
        alt.Chart(report)
        .mark_area(opacity=0.14, color=colors["fan"])
        .encode(
            x=alt.X("quarter_date:T", title="Target Quarter"),
            y=alt.Y("p10:Q", title="Simulated CPI YoY (%)"),
            y2="p90:Q",
            tooltip=["target_quarter:N", "horizon:Q", "p10:Q", "p90:Q"],
        )
    )
    inner_band = (
        alt.Chart(report)
        .mark_area(opacity=0.28, color=colors["fan"])
        .encode(
            x=alt.X("quarter_date:T", title="Target Quarter"),
            y=alt.Y("p25:Q", title="Simulated CPI YoY (%)"),
            y2="p75:Q",
            tooltip=["target_quarter:N", "horizon:Q", "p25:Q", "p75:Q"],
        )
    )
    median_line = (
        alt.Chart(report)
        .mark_line(strokeWidth=2, point=alt.OverlayMarkDef(size=45), color=colors["median"])
        .encode(
            x=alt.X("quarter_date:T", title="Target Quarter"),
            y=alt.Y("median:Q", title="Simulated CPI YoY (%)"),
            tooltip=["target_quarter:N", "horizon:Q", "median:Q"],
        )
    )
    return (
        (outer_band + inner_band + median_line)
        .properties(height=380)
        .configure_axis(gridColor=colors["grid"], labelColor=colors["muted"], titleColor=colors["muted"])
        .configure_view(strokeWidth=0)
    )


def caveat_for(label: str) -> tuple[str, str]:
    if label.startswith("SVAR"):
        return (
            "warning",
            "SVAR simulation fans come from Phase 1b VAR(2)-in-levels systems "
            "that still fail multivariate residual whiteness and normality "
            "diagnostics after COVID treatment checks and the block-bootstrap "
            "IRF fix; treat them as illustrative structural simulations, not "
            "precise causal estimates.",
        )
    return (
        "info",
        "This fan is an unconditional forward simulation from a model fit fresh "
        "on the full available history. It is distinct from the walk-forward "
        "accuracy and interval-coverage diagnostics shown on the Diagnostics page.",
    )


st.set_page_config(page_title="Methodology | Australian CPI Forecast", layout="wide")
st.title("Methodology")
st.caption(
    "Structured around CRISP-DM: Business Understanding, Data Understanding, "
    "Data Preparation, Modeling, Evaluation, Deployment."
)

st.header("1. Business Understanding")

st.markdown(
    """
    **Core question.** Can external macroeconomic indicators — unemployment, the cash
    rate, producer prices, commodity/oil prices, and business inflation expectations —
    improve Australian CPI forecasts relative to a seasonal-naive baseline and the RBA's
    own published forecasts, for both headline (`cpi_yoy`) and trimmed-mean
    (`trimmed_mean_cpi_yoy`) inflation?
    """
)

st.markdown(
    "**Success criteria** — defined precisely in §5 Evaluation; previewed here so "
    "every later section can be read against them:"
)

criteria_cols = st.columns(3)
with criteria_cols[0]:
    st.latex(r"\mathrm{RMSE} = \sqrt{\frac{1}{n}\sum_{i=1}^n (y_i - \hat y_i)^2}")
    st.caption("Point-forecast accuracy, per horizon, vs. seasonal-naive and RBA")
with criteria_cols[1]:
    st.latex(r"P(\text{lower} \le y \le \text{upper}) \approx 0.80")
    st.caption("Nominal 80% prediction-interval coverage")
with criteria_cols[2]:
    st.latex(r"\text{macro-F1} = \tfrac{1}{3}\sum_{c \in \{cut,hold,hike\}} F1_c")
    st.caption("RBA policy-action classifier, class-balanced")

st.warning(
    "**Out of scope.** The SVAR/scenario engine produces *illustrative* structural "
    "simulations, not causal point estimates — both systems fail multivariate residual "
    "whiteness and normality diagnostics even after COVID treatment and a block-bootstrap "
    "fix. Every scenario output downstream is labeled accordingly; this project does not "
    "claim identified causal effects."
)

st.header("4. Modeling — Simulation Fans")
st.caption(
    "Reads `reports/simulation_fan_*.csv`, generated by "
    "`python -m src.models.simulation_fan`, as local report artifacts rather "
    "than calling the live API."
)

with st.sidebar:
    selected_label = st.selectbox("Simulation fan", options=list(REPORT_PATHS))

selected_path = REPORT_PATHS[selected_label]
if not selected_path.exists():
    st.error(
        f"Missing simulation fan report: `{_display_path(selected_path)}`. "
        "Run `python -m src.models.simulation_fan` to regenerate it."
    )
    st.stop()

fan = _fan_frame(load_report(selected_path))
forecast_origin = str(fan["forecast_origin"].iloc[0]) if not fan.empty else "n/a"
target_column = str(fan["target_column"].iloc[0]) if not fan.empty else "n/a"

metric_cols = st.columns(3)
metric_cols[0].metric("Forecast origin", forecast_origin)
metric_cols[1].metric("Target", target_column)
metric_cols[2].metric("Horizons", f"{int(fan['horizon'].min())}-{int(fan['horizon'].max())}")

st.altair_chart(build_fan_chart(fan, _current_theme()), width="stretch")

caveat_level, caveat_text = caveat_for(selected_label)
if caveat_level == "warning":
    st.warning(caveat_text)
else:
    st.info(caveat_text)

with st.expander("Simulation fan table"):
    st.dataframe(fan.drop(columns=["quarter_date"]).round(4), width="stretch")
